language: node_js
cache:
  directories:
    - ~/.npm
    - "node_modules" #Cache node_modules for faster builds
    - dist
notifications:
  email: false
node_js:
  - "stable"
install: true
jobs:
  include:
    - stage: install dependencies
      script: npm install
    - stage: prepare build
      script: npm run prepareBuild
    - stage: predeploy
      script: npm run predeploy
    - stage: "deploy GH-PAGES to production"
      if: branch = master
      script: npm run deploy
    - stage: watch folder dist
      script: ls dist
    - stage: npm release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        before_script: cd dist
        script:
          - npx semantic-release
branches:
  only:
    - master
    - staging